export { default as DocumentCollectionEditor } from './DocumentCollectionEditor.vue'
export { default as DocumentEditFields } from './DocumentEditFields.vue'
export { quotationDocumentResource } from './quotation-document-resource'
export { useDocumentCollection } from './use-document-collection'
export type { DocumentRow, DocumentCollection, DocumentResource } from './use-document-collection'
