allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  msw: true
  vue-demi: true
  fsevents: true
  vite-plugin-theme-preprocessor@git+https://codeberg.org/My24Service/vite-plugin-theme-preprocessor.git: true
