export { default as OrderList } from './order/OrderList.vue'
export { default as OrderView } from './order/OrderView.vue'
export { default as WorkorderPage } from './workorder/WorkorderPage.vue'
export { default as OrderForm } from './form/OrderForm.vue'
export { default as OrdersSchedule } from './schedule/OrdersSchedule.vue'
