export { default as BuildingDetail } from './BuildingDetail.vue'
export { default as BuildingForm } from './BuildingForm.vue'
export { default as BuildingList } from './BuildingList.vue'
export { emptyBuilding, buildingFromRecord, FIELD_LABELS, validateBuilding, parseBuilding } from './schemas'
export type { BuildingFormValues, BuildingFieldErrors } from './schemas'
