#!/usr/bin/env node
/**
 * Where did the test run's time go?
 *
 * Vitest already prints the answer as the last line of every run:
 *
 *   Duration  60.04s (transform 32.55s, setup 10.92s, import 254.90s, tests 169.88s, environment 45.24s)
 *
 * Only `tests` is test work. The other four phases are paid once PER TEST FILE,
 * so in a 132-file suite a 1s per-file overhead is 132 CPU-seconds. This script
 * runs the suite, prints those phases against each other, and adds the one
 * thing the stock reporters do not show: how long each spec file spends
 * importing its own module graph before its first test runs.
 *
 * Usage:
 *   npm run test:profile                 # whole suite
 *   npm run test:profile -- tests/unit/features/member   # a subset
 *
 * Extra arguments are passed straight through to vitest, so `--maxWorkers=4`
 * and friends work too.
 */
import { spawnSync } from 'node:child_process'
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join, relative } from 'node:path'

const ROOT = process.cwd()
const scratch = mkdtempSync(join(tmpdir(), 'vitest-profile-'))
const taxFile = join(scratch, 'import-tax.jsonl')
const configPath = join(ROOT, '.vitest-profile.config.js')

const phasesOf = (line) => {
  const match = /Duration\s+([\d.]+)s\s*\(([^)]*)\)/.exec(line)
  if (!match) return null
  const phases = {}
  for (const part of match[2].split(',')) {
    const [, name, value] = /\s*([a-z]+)\s+([\d.]+)s/.exec(part) ?? []
    if (name) phases[name] = Number(value)
  }
  return { wall: Number(match[1]), phases }
}

const bar = (share) => '█'.repeat(Math.max(1, Math.round(share * 40)))

writeFileSync(
  configPath,
  `import base from './vitest.config.js'

// Generated by scripts/vitest-profile.mjs and deleted when it finishes.
export default {
  ...base,
  test: {
    ...base.test,
    setupFiles: ['tests/unit/support/import-tax-profiler.js', ...(base.test.setupFiles ?? [])],
  },
}
`,
)

let output = ''
try {
  const run = spawnSync(
    'npx',
    ['vitest', 'run', '--config', configPath, ...process.argv.slice(2)],
    { cwd: ROOT, encoding: 'utf8', env: { ...process.env, VITEST_IMPORT_TAX_FILE: taxFile } },
  )
  output = (run.stdout ?? '') + (run.stderr ?? '')

  if (run.status !== 0) {
    console.log(output.split('\n').slice(-40).join('\n'))
    console.error('\nvitest exited non-zero; not profiling a failing run.')
    process.exit(run.status ?? 1)
  }

  const summary = output
    .split('\n')
    .reverse()
    .map(phasesOf)
    .find(Boolean)

  console.log('\n' + '='.repeat(72))
  console.log('PHASES  (only "tests" is test work; the rest is per-file overhead)')
  console.log('='.repeat(72))

  if (!summary) {
    console.log(output.split('\n').slice(-20).join('\n'))
  } else {
    const total = Object.values(summary.phases).reduce((a, b) => a + b, 0)
    console.log(`wall ${summary.wall.toFixed(1)}s, ${total.toFixed(1)}s of CPU across all workers\n`)
    for (const [name, value] of Object.entries(summary.phases).sort((a, b) => b[1] - a[1])) {
      const share = value / total
      console.log(
        `  ${name.padEnd(12)} ${value.toFixed(1).padStart(8)}s  ${(share * 100).toFixed(1).padStart(5)}%  ${bar(share)}`,
      )
    }
  }

  if (existsSync(taxFile)) {
    const rows = readFileSync(taxFile, 'utf8')
      .trim()
      .split('\n')
      .filter(Boolean)
      .map((line) => JSON.parse(line))
      .sort((a, b) => b.ms - a.ms)

    const total = rows.reduce((a, r) => a + r.ms, 0)
    console.log(
      `\nIMPORT TAX PER SPEC FILE  (${rows.length} files, ${(total / 1000).toFixed(1)}s total)`,
    )
    console.log('='.repeat(72))
    for (const row of rows.slice(0, 15)) {
      console.log(`  ${(row.ms / 1000).toFixed(2).padStart(7)}s  ${relative(ROOT, row.path)}`)
    }
    const cheapest = rows[rows.length - 1]
    if (cheapest) {
      console.log(`\n  floor: ${(cheapest.ms / 1000).toFixed(2)}s (${relative(ROOT, cheapest.path)})`)
      console.log('  Everything above the floor is this spec\'s own module graph.')
    }
    console.log(
      '\n  A file far above the floor is importing far more than it tests.\n' +
        '  Check its imports for a feature barrel (which re-exports components).',
    )
  }
} finally {
  rmSync(configPath, { force: true })
  rmSync(scratch, { recursive: true, force: true })
}
