/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    'not-found': RouteRecordInfo<
      'not-found',
      '/:pathMatch*',
      { pathMatch?: ParamValueZeroOrMore<true> },
      { pathMatch?: ParamValueZeroOrMore<false> },
      | never
    >,
    'bim-frame': RouteRecordInfo<
      'bim-frame',
      '/bim',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'budget-dashboard': RouteRecordInfo<
      'budget-dashboard',
      '/budget',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'coming-soon': RouteRecordInfo<
      'coming-soon',
      '/coming-soon',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'company-activity': RouteRecordInfo<
      'company-activity',
      '/company/activity',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'users-apiusers': RouteRecordInfo<
      'users-apiusers',
      '/company/api-users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'apiuser-add': RouteRecordInfo<
      'apiuser-add',
      '/company/api-users/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'apiuser-edit': RouteRecordInfo<
      'apiuser-edit',
      '/company/api-users/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'company-branches': RouteRecordInfo<
      'company-branches',
      '/company/branches',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'company-branch-view': RouteRecordInfo<
      'company-branch-view',
      '/company/branches/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'company-branch-add': RouteRecordInfo<
      'company-branch-add',
      '/company/branches/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'company-branch-edit': RouteRecordInfo<
      'company-branch-edit',
      '/company/branches/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'company-my-branch': RouteRecordInfo<
      'company-my-branch',
      '/company/branches/form/my',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'company-budgets': RouteRecordInfo<
      'company-budgets',
      '/company/budgets',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'company-budget-view': RouteRecordInfo<
      'company-budget-view',
      '/company/budgets/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'company-my-budgets': RouteRecordInfo<
      'company-my-budgets',
      '/company/budgets/my',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'company-info': RouteRecordInfo<
      'company-info',
      '/company/company/info',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'company-settings': RouteRecordInfo<
      'company-settings',
      '/company/company/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'company-connector-gripp': RouteRecordInfo<
      'company-connector-gripp',
      '/company/connector-gripp',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'users-customerusers': RouteRecordInfo<
      'users-customerusers',
      '/company/customer-users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'customeruser-add': RouteRecordInfo<
      'customeruser-add',
      '/company/customer-users/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'customeruser-edit': RouteRecordInfo<
      'customeruser-edit',
      '/company/customer-users/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'company-dashboard': RouteRecordInfo<
      'company-dashboard',
      '/company/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'employee-dashboard': RouteRecordInfo<
      'employee-dashboard',
      '/company/employee-dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'users-employees': RouteRecordInfo<
      'users-employees',
      '/company/employee-users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'employee-add': RouteRecordInfo<
      'employee-add',
      '/company/employee-users/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'employee-edit': RouteRecordInfo<
      'employee-edit',
      '/company/employee-users/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'users-engineers': RouteRecordInfo<
      'users-engineers',
      '/company/engineer-users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'engineer-event-type-list': RouteRecordInfo<
      'engineer-event-type-list',
      '/company/engineer-users/event-types',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'engineer-event-type-add': RouteRecordInfo<
      'engineer-event-type-add',
      '/company/engineer-users/event-types/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'engineer-event-type-edit': RouteRecordInfo<
      'engineer-event-type-edit',
      '/company/engineer-users/event-types/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'engineer-event-list': RouteRecordInfo<
      'engineer-event-list',
      '/company/engineer-users/events',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'engineer-add': RouteRecordInfo<
      'engineer-add',
      '/company/engineer-users/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'engineer-edit': RouteRecordInfo<
      'engineer-edit',
      '/company/engineer-users/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'company-import-list': RouteRecordInfo<
      'company-import-list',
      '/company/import',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'company-import-add': RouteRecordInfo<
      'company-import-add',
      '/company/import/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'company-import-edit': RouteRecordInfo<
      'company-import-edit',
      '/company/import/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'company-import-preview': RouteRecordInfo<
      'company-import-preview',
      '/company/import/preview/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'company-partners-active': RouteRecordInfo<
      'company-partners-active',
      '/company/partners/active',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'company-partners-requests-received': RouteRecordInfo<
      'company-partners-requests-received',
      '/company/partners/requests-received',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'company-partners-requests-sent': RouteRecordInfo<
      'company-partners-requests-sent',
      '/company/partners/requests-sent',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'partner-request-add': RouteRecordInfo<
      'partner-request-add',
      '/company/partners/requests/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'company-pictures': RouteRecordInfo<
      'company-pictures',
      '/company/pictures',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'company-picture-add': RouteRecordInfo<
      'company-picture-add',
      '/company/pictures/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'company-picture-edit': RouteRecordInfo<
      'company-picture-edit',
      '/company/pictures/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'users-planningusers': RouteRecordInfo<
      'users-planningusers',
      '/company/planning-users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'planninguser-add': RouteRecordInfo<
      'planninguser-add',
      '/company/planning-users/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'planninguser-edit': RouteRecordInfo<
      'planninguser-edit',
      '/company/planning-users/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'users-salesusers': RouteRecordInfo<
      'users-salesusers',
      '/company/sales-users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'salesuser-add': RouteRecordInfo<
      'salesuser-add',
      '/company/sales-users/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'salesuser-edit': RouteRecordInfo<
      'salesuser-edit',
      '/company/sales-users/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'company-statuscodes': RouteRecordInfo<
      'company-statuscodes',
      '/company/statuscodes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'company-statuscodes-action-invoice-add': RouteRecordInfo<
      'company-statuscodes-action-invoice-add',
      '/company/statuscodes/action/invoice/add/:statuscode_pk',
      { statuscode_pk: ParamValue<true> },
      { statuscode_pk: ParamValue<false> },
      | never
    >,
    'company-statuscodes-action-invoice-edit': RouteRecordInfo<
      'company-statuscodes-action-invoice-edit',
      '/company/statuscodes/action/invoice/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'company-statuscodes-action-leave_hours-add': RouteRecordInfo<
      'company-statuscodes-action-leave_hours-add',
      '/company/statuscodes/action/leave_hours/add/:statuscode_pk',
      { statuscode_pk: ParamValue<true> },
      { statuscode_pk: ParamValue<false> },
      | never
    >,
    'company-statuscodes-action-leave_hours-edit': RouteRecordInfo<
      'company-statuscodes-action-leave_hours-edit',
      '/company/statuscodes/action/leave_hours/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'company-statuscodes-action-order-add': RouteRecordInfo<
      'company-statuscodes-action-order-add',
      '/company/statuscodes/action/order/add/:statuscode_pk',
      { statuscode_pk: ParamValue<true> },
      { statuscode_pk: ParamValue<false> },
      | never
    >,
    'company-statuscodes-action-order-edit': RouteRecordInfo<
      'company-statuscodes-action-order-edit',
      '/company/statuscodes/action/order/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'company-statuscodes-action-quotation-add': RouteRecordInfo<
      'company-statuscodes-action-quotation-add',
      '/company/statuscodes/action/quotation/add/:statuscode_pk',
      { statuscode_pk: ParamValue<true> },
      { statuscode_pk: ParamValue<false> },
      | never
    >,
    'company-statuscodes-action-quotation-edit': RouteRecordInfo<
      'company-statuscodes-action-quotation-edit',
      '/company/statuscodes/action/quotation/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'company-statuscodes-action-sick_leave-add': RouteRecordInfo<
      'company-statuscodes-action-sick_leave-add',
      '/company/statuscodes/action/sick_leave/add/:statuscode_pk',
      { statuscode_pk: ParamValue<true> },
      { statuscode_pk: ParamValue<false> },
      | never
    >,
    'company-statuscodes-action-sick_leave-edit': RouteRecordInfo<
      'company-statuscodes-action-sick_leave-edit',
      '/company/statuscodes/action/sick_leave/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'company-statuscodes-action-work_hours-add': RouteRecordInfo<
      'company-statuscodes-action-work_hours-add',
      '/company/statuscodes/action/work_hours/add/:statuscode_pk',
      { statuscode_pk: ParamValue<true> },
      { statuscode_pk: ParamValue<false> },
      | never
    >,
    'company-statuscodes-action-work_hours-edit': RouteRecordInfo<
      'company-statuscodes-action-work_hours-edit',
      '/company/statuscodes/action/work_hours/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'company-statuscodes-invoice': RouteRecordInfo<
      'company-statuscodes-invoice',
      '/company/statuscodes/invoice',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'company-statuscodes-invoice-add': RouteRecordInfo<
      'company-statuscodes-invoice-add',
      '/company/statuscodes/invoice/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'company-statuscodes-invoice-edit': RouteRecordInfo<
      'company-statuscodes-invoice-edit',
      '/company/statuscodes/invoice/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'company-statuscodes-leave_hours': RouteRecordInfo<
      'company-statuscodes-leave_hours',
      '/company/statuscodes/leave_hours',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'company-statuscodes-leave_hours-add': RouteRecordInfo<
      'company-statuscodes-leave_hours-add',
      '/company/statuscodes/leave_hours/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'company-statuscodes-leave_hours-edit': RouteRecordInfo<
      'company-statuscodes-leave_hours-edit',
      '/company/statuscodes/leave_hours/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'company-statuscodes-order': RouteRecordInfo<
      'company-statuscodes-order',
      '/company/statuscodes/order',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'company-statuscodes-order-add': RouteRecordInfo<
      'company-statuscodes-order-add',
      '/company/statuscodes/order/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'company-statuscodes-order-edit': RouteRecordInfo<
      'company-statuscodes-order-edit',
      '/company/statuscodes/order/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'company-statuscodes-quotation': RouteRecordInfo<
      'company-statuscodes-quotation',
      '/company/statuscodes/quotation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'company-statuscodes-quotation-add': RouteRecordInfo<
      'company-statuscodes-quotation-add',
      '/company/statuscodes/quotation/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'company-statuscodes-quotation-edit': RouteRecordInfo<
      'company-statuscodes-quotation-edit',
      '/company/statuscodes/quotation/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'company-statuscodes-sick_leave': RouteRecordInfo<
      'company-statuscodes-sick_leave',
      '/company/statuscodes/sick_leave',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'company-statuscodes-sick_leave-add': RouteRecordInfo<
      'company-statuscodes-sick_leave-add',
      '/company/statuscodes/sick_leave/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'company-statuscodes-sick_leave-edit': RouteRecordInfo<
      'company-statuscodes-sick_leave-edit',
      '/company/statuscodes/sick_leave/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'company-statuscodes-work_hours': RouteRecordInfo<
      'company-statuscodes-work_hours',
      '/company/statuscodes/work_hours',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'company-statuscodes-work_hours-add': RouteRecordInfo<
      'company-statuscodes-work_hours-add',
      '/company/statuscodes/work_hours/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'company-statuscodes-work_hours-edit': RouteRecordInfo<
      'company-statuscodes-work_hours-edit',
      '/company/statuscodes/work_hours/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'users-studentusers': RouteRecordInfo<
      'users-studentusers',
      '/company/student-users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'studentuser-add': RouteRecordInfo<
      'studentuser-add',
      '/company/student-users/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'studentuser-edit': RouteRecordInfo<
      'studentuser-edit',
      '/company/student-users/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'studentuser-register': RouteRecordInfo<
      'studentuser-register',
      '/company/student-users/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'studentuser-reset-password': RouteRecordInfo<
      'studentuser-reset-password',
      '/company/student-users/register/reset-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'studentuser-verify': RouteRecordInfo<
      'studentuser-verify',
      '/company/student-users/register/verify',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'studentuser-detail': RouteRecordInfo<
      'studentuser-detail',
      '/company/student-users/view/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'company-teamleader-callback': RouteRecordInfo<
      'company-teamleader-callback',
      '/company/teamleader/callback',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'company-teamleader-settings': RouteRecordInfo<
      'company-teamleader-settings',
      '/company/teamleader/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'company-templates': RouteRecordInfo<
      'company-templates',
      '/company/templates',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'customer-template-add': RouteRecordInfo<
      'customer-template-add',
      '/company/templates/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'customer-template-edit': RouteRecordInfo<
      'customer-template-edit',
      '/company/templates/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'company-time-registration': RouteRecordInfo<
      'company-time-registration',
      '/company/time-registration',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'company-time-registration-detail': RouteRecordInfo<
      'company-time-registration-detail',
      '/company/time-registration/detail/:user_id',
      { user_id: ParamValue<true> },
      { user_id: ParamValue<false> },
      | never
    >,
    'leave-list': RouteRecordInfo<
      'leave-list',
      '/company/time-registration/leave',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'leave-list-add': RouteRecordInfo<
      'leave-list-add',
      '/company/time-registration/leave/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'leave-edit': RouteRecordInfo<
      'leave-edit',
      '/company/time-registration/leave/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'leave-requests': RouteRecordInfo<
      'leave-requests',
      '/company/time-registration/leave/requests',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'leave-types': RouteRecordInfo<
      'leave-types',
      '/company/time-registration/leave/types',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'sick-leave-list': RouteRecordInfo<
      'sick-leave-list',
      '/company/time-registration/sick-leave',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'sick-leave-list-add': RouteRecordInfo<
      'sick-leave-list-add',
      '/company/time-registration/sick-leave/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'sick-leave-list-edit': RouteRecordInfo<
      'sick-leave-list-edit',
      '/company/time-registration/sick-leave/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'unconfirmed-sick-leave': RouteRecordInfo<
      'unconfirmed-sick-leave',
      '/company/time-registration/sick-leave/unconfirmed',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'customer-list': RouteRecordInfo<
      'customer-list',
      '/customers/customers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'customer-view': RouteRecordInfo<
      'customer-view',
      '/customers/customers/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'customer-add': RouteRecordInfo<
      'customer-add',
      '/customers/customers/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'customer-edit': RouteRecordInfo<
      'customer-edit',
      '/customers/customers/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'customer-dashboard': RouteRecordInfo<
      'customer-dashboard',
      '/customers/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'customers-equipment-list': RouteRecordInfo<
      'customers-equipment-list',
      '/customers/equipment',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'customers-equipment-view': RouteRecordInfo<
      'customers-equipment-view',
      '/customers/equipment/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'customers-equipment-view-facility': RouteRecordInfo<
      'customers-equipment-view-facility',
      '/customers/equipment/facility/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'customers-equipment-edit-facility': RouteRecordInfo<
      'customers-equipment-edit-facility',
      '/customers/equipment/facility/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'customers-equipment-add': RouteRecordInfo<
      'customers-equipment-add',
      '/customers/equipment/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'customers-equipment-edit': RouteRecordInfo<
      'customers-equipment-edit',
      '/customers/equipment/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'customers-equipment-view-technical': RouteRecordInfo<
      'customers-equipment-view-technical',
      '/customers/equipment/technical/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'customers-equipment-edit-technical': RouteRecordInfo<
      'customers-equipment-edit-technical',
      '/customers/equipment/technical/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'customers-location-list': RouteRecordInfo<
      'customers-location-list',
      '/customers/locations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'customers-location-view': RouteRecordInfo<
      'customers-location-view',
      '/customers/locations/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'customers-location-add': RouteRecordInfo<
      'customers-location-add',
      '/customers/locations/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'customers-location-edit': RouteRecordInfo<
      'customers-location-edit',
      '/customers/locations/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'maintenance-contracts': RouteRecordInfo<
      'maintenance-contracts',
      '/customers/maintenance-contracts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'maintenance-contract-add': RouteRecordInfo<
      'maintenance-contract-add',
      '/customers/maintenance-contracts/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'maintenance-contract-edit': RouteRecordInfo<
      'maintenance-contract-edit',
      '/customers/maintenance-contracts/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'maintenance-contract-view': RouteRecordInfo<
      'maintenance-contract-view',
      '/customers/maintenance-contracts/view/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'dashboard': RouteRecordInfo<
      'dashboard',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'equipment-building-list': RouteRecordInfo<
      'equipment-building-list',
      '/equipment/buildings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'equipment-building-view': RouteRecordInfo<
      'equipment-building-view',
      '/equipment/buildings/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'equipment-building-add': RouteRecordInfo<
      'equipment-building-add',
      '/equipment/buildings/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'equipment-building-edit': RouteRecordInfo<
      'equipment-building-edit',
      '/equipment/buildings/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'equipment-equipment-view': RouteRecordInfo<
      'equipment-equipment-view',
      '/equipment/equipment/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'equipment-equipment-list': RouteRecordInfo<
      'equipment-equipment-list',
      '/equipment/equipment/:type',
      { type: ParamValue<true> },
      { type: ParamValue<false> },
      | never
    >,
    'equipment-equipment-view-facility': RouteRecordInfo<
      'equipment-equipment-view-facility',
      '/equipment/equipment/facility/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'equipment-equipment-edit-facility': RouteRecordInfo<
      'equipment-equipment-edit-facility',
      '/equipment/equipment/facility/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'equipment-equipment-add': RouteRecordInfo<
      'equipment-equipment-add',
      '/equipment/equipment/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'equipment-equipment-edit': RouteRecordInfo<
      'equipment-equipment-edit',
      '/equipment/equipment/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'equipment-equipment-view-technical': RouteRecordInfo<
      'equipment-equipment-view-technical',
      '/equipment/equipment/technical/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'equipment-equipment-edit-technical': RouteRecordInfo<
      'equipment-equipment-edit-technical',
      '/equipment/equipment/technical/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'equipment-location-list': RouteRecordInfo<
      'equipment-location-list',
      '/equipment/locations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'equipment-location-view': RouteRecordInfo<
      'equipment-location-view',
      '/equipment/locations/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'equipment-location-add': RouteRecordInfo<
      'equipment-location-add',
      '/equipment/locations/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'equipment-location-edit': RouteRecordInfo<
      'equipment-location-edit',
      '/equipment/locations/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'material-list': RouteRecordInfo<
      'material-list',
      '/inventory/materials',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'material-add': RouteRecordInfo<
      'material-add',
      '/inventory/materials/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'material-edit': RouteRecordInfo<
      'material-edit',
      '/inventory/materials/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'material-view': RouteRecordInfo<
      'material-view',
      '/inventory/materials/view/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'material-move': RouteRecordInfo<
      'material-move',
      '/inventory/move-material',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'mutation-list': RouteRecordInfo<
      'mutation-list',
      '/inventory/mutations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'mutation-add': RouteRecordInfo<
      'mutation-add',
      '/inventory/mutations/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'purchaseorder-entry-list': RouteRecordInfo<
      'purchaseorder-entry-list',
      '/inventory/purchaseorder-entries',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'purchaseorder-entry-add': RouteRecordInfo<
      'purchaseorder-entry-add',
      '/inventory/purchaseorder-entries/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'purchaseorder-entry-edit': RouteRecordInfo<
      'purchaseorder-entry-edit',
      '/inventory/purchaseorder-entries/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'purchaseorder-entry-view': RouteRecordInfo<
      'purchaseorder-entry-view',
      '/inventory/purchaseorder-entries/view/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'purchaseorder-list': RouteRecordInfo<
      'purchaseorder-list',
      '/inventory/purchaseorders',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'purchaseorder-add': RouteRecordInfo<
      'purchaseorder-add',
      '/inventory/purchaseorders/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'purchaseorder-edit': RouteRecordInfo<
      'purchaseorder-edit',
      '/inventory/purchaseorders/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'purchaseorder-add-from-reservation': RouteRecordInfo<
      'purchaseorder-add-from-reservation',
      '/inventory/purchaseorders/from/reservation/:reservation_pk',
      { reservation_pk: ParamValue<true> },
      { reservation_pk: ParamValue<false> },
      | never
    >,
    'purchaseorder-view': RouteRecordInfo<
      'purchaseorder-view',
      '/inventory/purchaseorders/view/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'inventory-stats': RouteRecordInfo<
      'inventory-stats',
      '/inventory/stats',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'inventory-stats-table': RouteRecordInfo<
      'inventory-stats-table',
      '/inventory/stats-table',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'stock-location-list': RouteRecordInfo<
      'stock-location-list',
      '/inventory/stock-locations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'stock-location-add': RouteRecordInfo<
      'stock-location-add',
      '/inventory/stock-locations/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'stock-location-edit': RouteRecordInfo<
      'stock-location-edit',
      '/inventory/stock-locations/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'stock-location-view': RouteRecordInfo<
      'stock-location-view',
      '/inventory/stock-locations/view/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'supplier-reservation-list': RouteRecordInfo<
      'supplier-reservation-list',
      '/inventory/supplier-reservations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'supplier-reservation-add': RouteRecordInfo<
      'supplier-reservation-add',
      '/inventory/supplier-reservations/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'supplier-reservation-edit': RouteRecordInfo<
      'supplier-reservation-edit',
      '/inventory/supplier-reservations/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'supplier-reservation-view': RouteRecordInfo<
      'supplier-reservation-view',
      '/inventory/supplier-reservations/view/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'supplier-list': RouteRecordInfo<
      'supplier-list',
      '/inventory/suppliers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'supplier-add': RouteRecordInfo<
      'supplier-add',
      '/inventory/suppliers/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'supplier-edit': RouteRecordInfo<
      'supplier-edit',
      '/inventory/suppliers/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'supplier-view': RouteRecordInfo<
      'supplier-view',
      '/inventory/suppliers/view/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'invoice-list': RouteRecordInfo<
      'invoice-list',
      '/invoices/invoices',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'invoice-view': RouteRecordInfo<
      'invoice-view',
      '/invoices/invoices/view/:uuid',
      { uuid: ParamValue<true> },
      { uuid: ParamValue<false> },
      | never
    >,
    'preliminary-invoices': RouteRecordInfo<
      'preliminary-invoices',
      '/invoices/preliminary',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'invoice-edit': RouteRecordInfo<
      'invoice-edit',
      '/invoices/preliminary/form/:pk/order/:uuid',
      { pk: ParamValue<true>, uuid: ParamValue<true> },
      { pk: ParamValue<false>, uuid: ParamValue<false> },
      | never
    >,
    'invoice-create': RouteRecordInfo<
      'invoice-create',
      '/invoices/preliminary/form/:uuid',
      { uuid: ParamValue<true> },
      { uuid: ParamValue<false> },
      | never
    >,
    'invoices-sent': RouteRecordInfo<
      'invoices-sent',
      '/invoices/sent',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'invoice-send': RouteRecordInfo<
      'invoice-send',
      '/invoices/sent/form/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'contract-list': RouteRecordInfo<
      'contract-list',
      '/members/contracts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'contract-add': RouteRecordInfo<
      'contract-add',
      '/members/contracts/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'contract-edit': RouteRecordInfo<
      'contract-edit',
      '/members/contracts/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'member-deleted-list': RouteRecordInfo<
      'member-deleted-list',
      '/members/deleted-members',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'member-list': RouteRecordInfo<
      'member-list',
      '/members/members',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'member-add': RouteRecordInfo<
      'member-add',
      '/members/members/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'member-edit': RouteRecordInfo<
      'member-edit',
      '/members/members/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'member-request': RouteRecordInfo<
      'member-request',
      '/members/members/request-form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'module-part-list': RouteRecordInfo<
      'module-part-list',
      '/members/module-parts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'module-part-add': RouteRecordInfo<
      'module-part-add',
      '/members/module-parts/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'module-part-edit': RouteRecordInfo<
      'module-part-edit',
      '/members/module-parts/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'module-list': RouteRecordInfo<
      'module-list',
      '/members/modules',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'module-add': RouteRecordInfo<
      'module-add',
      '/members/modules/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'module-edit': RouteRecordInfo<
      'module-edit',
      '/members/modules/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'member-requested-list': RouteRecordInfo<
      'member-requested-list',
      '/members/requested-members',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'mobile-assigned-finished': RouteRecordInfo<
      'mobile-assigned-finished',
      '/mobile/assigned-finished',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'mobile-dispatch': RouteRecordInfo<
      'mobile-dispatch',
      '/mobile/dispatch/:assignModeProp?',
      { assignModeProp?: ParamValueZeroOrOne<true> },
      { assignModeProp?: ParamValueZeroOrOne<false> },
      | never
    >,
    'mobile-map': RouteRecordInfo<
      'mobile-map',
      '/mobile/map',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'mobile-orders': RouteRecordInfo<
      'mobile-orders',
      '/mobile/orders',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'mobile-orders-finished': RouteRecordInfo<
      'mobile-orders-finished',
      '/mobile/orders-finished',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'mobile-orders-in-progress': RouteRecordInfo<
      'mobile-orders-in-progress',
      '/mobile/orders-in-progress',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'mobile-timesheet': RouteRecordInfo<
      'mobile-timesheet',
      '/mobile/timesheet',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'mobile-timesheet-detail': RouteRecordInfo<
      'mobile-timesheet-detail',
      '/mobile/timesheet/:user_id',
      { user_id: ParamValue<true> },
      { user_id: ParamValue<false> },
      | never
    >,
    'mobile-trip-availability': RouteRecordInfo<
      'mobile-trip-availability',
      '/mobile/trip-availability',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'mobile-trip-availability-detail': RouteRecordInfo<
      'mobile-trip-availability-detail',
      '/mobile/trip-availability/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'mobile-trips': RouteRecordInfo<
      'mobile-trips',
      '/mobile/trips',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'mobile-trips-add': RouteRecordInfo<
      'mobile-trips-add',
      '/mobile/trips/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'mobile-trips-edit': RouteRecordInfo<
      'mobile-trips-edit',
      '/mobile/trips/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'no-access': RouteRecordInfo<
      'no-access',
      '/no-access',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'order-filter-list': RouteRecordInfo<
      'order-filter-list',
      '/orders/filter',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'order-filter-add': RouteRecordInfo<
      'order-filter-add',
      '/orders/filter/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'order-filter-edit': RouteRecordInfo<
      'order-filter-edit',
      '/orders/filter/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'order-month-stats': RouteRecordInfo<
      'order-month-stats',
      '/orders/month-stats',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'order-list': RouteRecordInfo<
      'order-list',
      '/orders/orders',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'orders-not-accepted': RouteRecordInfo<
      'orders-not-accepted',
      '/orders/orders-not-accepted',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'order-detail': RouteRecordInfo<
      'order-detail',
      '/orders/orders/detail/:uuid',
      { uuid: ParamValue<true> },
      { uuid: ParamValue<false> },
      | never
    >,
    'order-add': RouteRecordInfo<
      'order-add',
      '/orders/orders/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'order-add-maintenance': RouteRecordInfo<
      'order-add-maintenance',
      '/orders/orders/form-maintenance',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'order-add-quotation': RouteRecordInfo<
      'order-add-quotation',
      '/orders/orders/form-maintenance/:quotation_id',
      { quotation_id: ParamValue<true> },
      { quotation_id: ParamValue<false> },
      | never
    >,
    'order-edit': RouteRecordInfo<
      'order-edit',
      '/orders/orders/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'order-view': RouteRecordInfo<
      'order-view',
      '/orders/orders/view/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'workorder-view': RouteRecordInfo<
      'workorder-view',
      '/orders/orders/workorder/:uuid',
      { uuid: ParamValue<true> },
      { uuid: ParamValue<false> },
      | never
    >,
    'orders-schedule': RouteRecordInfo<
      'orders-schedule',
      '/orders/schedule',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'orders-schedule-params': RouteRecordInfo<
      'orders-schedule-params',
      '/orders/schedule/:start/:end',
      { end: ParamValue<true>, start: ParamValue<true> },
      { end: ParamValue<false>, start: ParamValue<false> },
      | never
    >,
    'order-year-stats': RouteRecordInfo<
      'order-year-stats',
      '/orders/year-stats',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'dashboard-overview': RouteRecordInfo<
      'dashboard-overview',
      '/overview',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'preliminary-quotations': RouteRecordInfo<
      'preliminary-quotations',
      '/quotations/preliminary',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'quotation-add': RouteRecordInfo<
      'quotation-add',
      '/quotations/preliminary/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'quotation-edit-preliminary': RouteRecordInfo<
      'quotation-edit-preliminary',
      '/quotations/preliminary/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'quotation-list': RouteRecordInfo<
      'quotation-list',
      '/quotations/quotations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'quotation-detail': RouteRecordInfo<
      'quotation-detail',
      '/quotations/quotations/detail/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'quotation-edit': RouteRecordInfo<
      'quotation-edit',
      '/quotations/quotations/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'quotation-view': RouteRecordInfo<
      'quotation-view',
      '/quotations/quotations/view/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'quotations-sent': RouteRecordInfo<
      'quotations-sent',
      '/quotations/sent',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'quotation-send': RouteRecordInfo<
      'quotation-send',
      '/quotations/sent/form/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'quotations-sent-view': RouteRecordInfo<
      'quotations-sent-view',
      '/quotations/sent/view/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'reset-password': RouteRecordInfo<
      'reset-password',
      '/reset-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'reset-password-confirm': RouteRecordInfo<
      'reset-password-confirm',
      '/reset-password-confirm',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'settings-branches': RouteRecordInfo<
      'settings-branches',
      '/settings/branches',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'settings-branch-view': RouteRecordInfo<
      'settings-branch-view',
      '/settings/branches/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'settings-branch-add': RouteRecordInfo<
      'settings-branch-add',
      '/settings/branches/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'settings-branch-edit': RouteRecordInfo<
      'settings-branch-edit',
      '/settings/branches/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'settings-my-branch': RouteRecordInfo<
      'settings-my-branch',
      '/settings/branches/form/my',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'settings-company': RouteRecordInfo<
      'settings-company',
      '/settings/company',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'settings-company-import-list': RouteRecordInfo<
      'settings-company-import-list',
      '/settings/company/import',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'settings-company-import-add': RouteRecordInfo<
      'settings-company-import-add',
      '/settings/company/import/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'settings-company-import-edit': RouteRecordInfo<
      'settings-company-import-edit',
      '/settings/company/import/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'settings-company-import-preview': RouteRecordInfo<
      'settings-company-import-preview',
      '/settings/company/import/preview/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'settings-equipment-view': RouteRecordInfo<
      'settings-equipment-view',
      '/settings/equipment/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'settings-equipment-list': RouteRecordInfo<
      'settings-equipment-list',
      '/settings/equipment/:type',
      { type: ParamValue<true> },
      { type: ParamValue<false> },
      | never
    >,
    'settings-equipment-view-facility': RouteRecordInfo<
      'settings-equipment-view-facility',
      '/settings/equipment/facility/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'settings-equipment-edit-facility': RouteRecordInfo<
      'settings-equipment-edit-facility',
      '/settings/equipment/facility/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'settings-equipment-add': RouteRecordInfo<
      'settings-equipment-add',
      '/settings/equipment/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'settings-equipment-edit': RouteRecordInfo<
      'settings-equipment-edit',
      '/settings/equipment/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'settings-equipment-view-technical': RouteRecordInfo<
      'settings-equipment-view-technical',
      '/settings/equipment/technical/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'settings-equipment-edit-technical': RouteRecordInfo<
      'settings-equipment-edit-technical',
      '/settings/equipment/technical/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'settings-order-filter-list': RouteRecordInfo<
      'settings-order-filter-list',
      '/settings/filter',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'settings-order-filter-add': RouteRecordInfo<
      'settings-order-filter-add',
      '/settings/filter/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'settings-order-filter-edit': RouteRecordInfo<
      'settings-order-filter-edit',
      '/settings/filter/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'settings-location-list': RouteRecordInfo<
      'settings-location-list',
      '/settings/locations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'settings-location-view': RouteRecordInfo<
      'settings-location-view',
      '/settings/locations/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'settings-location-add': RouteRecordInfo<
      'settings-location-add',
      '/settings/locations/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'settings-location-edit': RouteRecordInfo<
      'settings-location-edit',
      '/settings/locations/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'settings-invoice-statuscode-list': RouteRecordInfo<
      'settings-invoice-statuscode-list',
      '/settings/statuscodes/invoice',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'settings-invoice-statuscode-action-add': RouteRecordInfo<
      'settings-invoice-statuscode-action-add',
      '/settings/statuscodes/invoice/action/add/:statuscode_pk',
      { statuscode_pk: ParamValue<true> },
      { statuscode_pk: ParamValue<false> },
      | never
    >,
    'settings-invoice-statuscode-action-edit': RouteRecordInfo<
      'settings-invoice-statuscode-action-edit',
      '/settings/statuscodes/invoice/action/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'settings-invoice-statuscode-add': RouteRecordInfo<
      'settings-invoice-statuscode-add',
      '/settings/statuscodes/invoice/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'settings-invoice-statuscode-edit': RouteRecordInfo<
      'settings-invoice-statuscode-edit',
      '/settings/statuscodes/invoice/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'settings-leave_hours-statuscode-list': RouteRecordInfo<
      'settings-leave_hours-statuscode-list',
      '/settings/statuscodes/leave_hours',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'settings-leave_hours-statuscode-action-add': RouteRecordInfo<
      'settings-leave_hours-statuscode-action-add',
      '/settings/statuscodes/leave_hours/action/add/:statuscode_pk',
      { statuscode_pk: ParamValue<true> },
      { statuscode_pk: ParamValue<false> },
      | never
    >,
    'settings-leave_hours-statuscode-action-edit': RouteRecordInfo<
      'settings-leave_hours-statuscode-action-edit',
      '/settings/statuscodes/leave_hours/action/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'settings-leave_hours-statuscode-add': RouteRecordInfo<
      'settings-leave_hours-statuscode-add',
      '/settings/statuscodes/leave_hours/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'settings-leave_hours-statuscode-edit': RouteRecordInfo<
      'settings-leave_hours-statuscode-edit',
      '/settings/statuscodes/leave_hours/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'settings-order-statuscode-list': RouteRecordInfo<
      'settings-order-statuscode-list',
      '/settings/statuscodes/order',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'settings-order-statuscode-action-add': RouteRecordInfo<
      'settings-order-statuscode-action-add',
      '/settings/statuscodes/order/action/add/:statuscode_pk',
      { statuscode_pk: ParamValue<true> },
      { statuscode_pk: ParamValue<false> },
      | never
    >,
    'settings-order-statuscode-action-edit': RouteRecordInfo<
      'settings-order-statuscode-action-edit',
      '/settings/statuscodes/order/action/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'settings-order-statuscode-add': RouteRecordInfo<
      'settings-order-statuscode-add',
      '/settings/statuscodes/order/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'settings-order-statuscode-edit': RouteRecordInfo<
      'settings-order-statuscode-edit',
      '/settings/statuscodes/order/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'settings-quotation-statuscode-list': RouteRecordInfo<
      'settings-quotation-statuscode-list',
      '/settings/statuscodes/quotation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'settings-quotation-statuscode-action-add': RouteRecordInfo<
      'settings-quotation-statuscode-action-add',
      '/settings/statuscodes/quotation/action/add/:statuscode_pk',
      { statuscode_pk: ParamValue<true> },
      { statuscode_pk: ParamValue<false> },
      | never
    >,
    'settings-quotation-statuscode-action-edit': RouteRecordInfo<
      'settings-quotation-statuscode-action-edit',
      '/settings/statuscodes/quotation/action/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'settings-quotation-statuscode-add': RouteRecordInfo<
      'settings-quotation-statuscode-add',
      '/settings/statuscodes/quotation/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'settings-quotation-statuscode-edit': RouteRecordInfo<
      'settings-quotation-statuscode-edit',
      '/settings/statuscodes/quotation/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'settings-sick_leave-statuscode-list': RouteRecordInfo<
      'settings-sick_leave-statuscode-list',
      '/settings/statuscodes/sick_leave',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'settings-sick_leave-statuscode-action-add': RouteRecordInfo<
      'settings-sick_leave-statuscode-action-add',
      '/settings/statuscodes/sick_leave/action/add/:statuscode_pk',
      { statuscode_pk: ParamValue<true> },
      { statuscode_pk: ParamValue<false> },
      | never
    >,
    'settings-sick_leave-statuscode-action-edit': RouteRecordInfo<
      'settings-sick_leave-statuscode-action-edit',
      '/settings/statuscodes/sick_leave/action/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'settings-sick_leave-statuscode-add': RouteRecordInfo<
      'settings-sick_leave-statuscode-add',
      '/settings/statuscodes/sick_leave/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'settings-sick_leave-statuscode-edit': RouteRecordInfo<
      'settings-sick_leave-statuscode-edit',
      '/settings/statuscodes/sick_leave/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'settings-work_hours-statuscode-list': RouteRecordInfo<
      'settings-work_hours-statuscode-list',
      '/settings/statuscodes/work_hours',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'settings-work_hours-statuscode-action-add': RouteRecordInfo<
      'settings-work_hours-statuscode-action-add',
      '/settings/statuscodes/work_hours/action/add/:statuscode_pk',
      { statuscode_pk: ParamValue<true> },
      { statuscode_pk: ParamValue<false> },
      | never
    >,
    'settings-work_hours-statuscode-action-edit': RouteRecordInfo<
      'settings-work_hours-statuscode-action-edit',
      '/settings/statuscodes/work_hours/action/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'settings-work_hours-statuscode-add': RouteRecordInfo<
      'settings-work_hours-statuscode-add',
      '/settings/statuscodes/work_hours/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'settings-work_hours-statuscode-edit': RouteRecordInfo<
      'settings-work_hours-statuscode-edit',
      '/settings/statuscodes/work_hours/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'settings-users-employees': RouteRecordInfo<
      'settings-users-employees',
      '/settings/users/employee-users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'settings-employee-add': RouteRecordInfo<
      'settings-employee-add',
      '/settings/users/employee-users/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'settings-employee-edit': RouteRecordInfo<
      'settings-employee-edit',
      '/settings/users/employee-users/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'settings-users-planningusers': RouteRecordInfo<
      'settings-users-planningusers',
      '/settings/users/planning-users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'settings-planninguser-add': RouteRecordInfo<
      'settings-planninguser-add',
      '/settings/users/planning-users/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'settings-planninguser-edit': RouteRecordInfo<
      'settings-planninguser-edit',
      '/settings/users/planning-users/form/:pk',
      { pk: ParamValue<true> },
      { pk: ParamValue<false> },
      | never
    >,
    'webshop': RouteRecordInfo<
      'webshop',
      '/webshop',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/views/shared/NotFound.vue': {
      routes:
        | 'not-found'
      views:
        | never
      pathParamNames:
        | 'pathMatch'
    }
    'src/views/bim/BIMFrame.vue': {
      routes:
        | 'bim-frame'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/shared/ComingSoon.vue': {
      routes:
        | 'budget-dashboard'
        | 'coming-soon'
        | 'company-my-budgets'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/company/activity/ActivityList.vue': {
      routes:
        | 'company-activity'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/user/api/ApiUserList.vue': {
      routes:
        | 'users-apiusers'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/user/api/ApiUserForm.vue': {
      routes:
        | 'apiuser-add'
        | 'apiuser-edit'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/features/company/branch/BranchList.vue': {
      routes:
        | 'company-branches'
        | 'settings-branches'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/company/branch/BranchView.vue': {
      routes:
        | 'company-branch-view'
        | 'employee-dashboard'
        | 'settings-branch-view'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/features/company/branch/BranchForm.vue': {
      routes:
        | 'company-branch-add'
        | 'company-branch-edit'
        | 'company-my-branch'
        | 'settings-branch-add'
        | 'settings-branch-edit'
        | 'settings-my-branch'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/features/company/budget/BudgetList.vue': {
      routes:
        | 'company-budgets'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/company/budget/BudgetView.vue': {
      routes:
        | 'company-budget-view'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/features/company/info/CompanyInfo.vue': {
      routes:
        | 'company-info'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/member/settings/SettingsForm.vue': {
      routes:
        | 'company-settings'
        | 'settings-company'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/company/ConnectorGrippSettings.vue': {
      routes:
        | 'company-connector-gripp'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/user/customer/CustomerUserList.vue': {
      routes:
        | 'users-customerusers'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/user/customer/CustomerUserForm.vue': {
      routes:
        | 'customeruser-add'
        | 'customeruser-edit'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/views/company/CompanyDashboard.vue': {
      routes:
        | 'company-dashboard'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/user/employee/EmployeeUserList.vue': {
      routes:
        | 'settings-users-employees'
        | 'users-employees'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/user/employee/EmployeeUserForm.vue': {
      routes:
        | 'employee-add'
        | 'employee-edit'
        | 'settings-employee-add'
        | 'settings-employee-edit'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/features/user/engineer/EngineerUserList.vue': {
      routes:
        | 'users-engineers'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/field-service/engineer-event/EngineerEventTypeList.vue': {
      routes:
        | 'engineer-event-type-list'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/field-service/engineer-event/EngineerEventTypeForm.vue': {
      routes:
        | 'engineer-event-type-add'
        | 'engineer-event-type-edit'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/features/field-service/engineer-event/EngineerEventList.vue': {
      routes:
        | 'engineer-event-list'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/user/engineer/EngineerUserForm.vue': {
      routes:
        | 'engineer-add'
        | 'engineer-edit'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/features/company/import/ImportList.vue': {
      routes:
        | 'company-import-list'
        | 'settings-company-import-list'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/company/import/ImportForm.vue': {
      routes:
        | 'company-import-add'
        | 'company-import-edit'
        | 'settings-company-import-add'
        | 'settings-company-import-edit'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/features/company/import/ImportPreview.vue': {
      routes:
        | 'company-import-preview'
        | 'settings-company-import-preview'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/features/company/partner/PartnerList.vue': {
      routes:
        | 'company-partners-active'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/company/partner/PartnerRequestsReceivedList.vue': {
      routes:
        | 'company-partners-requests-received'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/company/partner/PartnerRequestsSentList.vue': {
      routes:
        | 'company-partners-requests-sent'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/company/partner/PartnerRequestsSentForm.vue': {
      routes:
        | 'partner-request-add'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/company/picture/PictureList.vue': {
      routes:
        | 'company-pictures'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/company/picture/PictureForm.vue': {
      routes:
        | 'company-picture-add'
        | 'company-picture-edit'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/features/user/planning/PlanningUserList.vue': {
      routes:
        | 'settings-users-planningusers'
        | 'users-planningusers'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/user/planning/PlanningUserForm.vue': {
      routes:
        | 'planninguser-add'
        | 'planninguser-edit'
        | 'settings-planninguser-add'
        | 'settings-planninguser-edit'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/features/user/sales/SalesUserList.vue': {
      routes:
        | 'users-salesusers'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/user/sales/SalesUserForm.vue': {
      routes:
        | 'salesuser-add'
        | 'salesuser-edit'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/features/statuscode/StatuscodeList.vue': {
      routes:
        | 'company-statuscodes'
        | 'company-statuscodes-invoice'
        | 'company-statuscodes-leave_hours'
        | 'company-statuscodes-order'
        | 'company-statuscodes-quotation'
        | 'company-statuscodes-sick_leave'
        | 'company-statuscodes-work_hours'
        | 'settings-invoice-statuscode-list'
        | 'settings-leave_hours-statuscode-list'
        | 'settings-order-statuscode-list'
        | 'settings-quotation-statuscode-list'
        | 'settings-sick_leave-statuscode-list'
        | 'settings-work_hours-statuscode-list'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/statuscode/action/ActionForm.vue': {
      routes:
        | 'company-statuscodes-action-invoice-add'
        | 'company-statuscodes-action-invoice-edit'
        | 'company-statuscodes-action-leave_hours-add'
        | 'company-statuscodes-action-leave_hours-edit'
        | 'company-statuscodes-action-order-add'
        | 'company-statuscodes-action-order-edit'
        | 'company-statuscodes-action-quotation-add'
        | 'company-statuscodes-action-quotation-edit'
        | 'company-statuscodes-action-sick_leave-add'
        | 'company-statuscodes-action-sick_leave-edit'
        | 'company-statuscodes-action-work_hours-add'
        | 'company-statuscodes-action-work_hours-edit'
        | 'settings-invoice-statuscode-action-add'
        | 'settings-invoice-statuscode-action-edit'
        | 'settings-leave_hours-statuscode-action-add'
        | 'settings-leave_hours-statuscode-action-edit'
        | 'settings-order-statuscode-action-add'
        | 'settings-order-statuscode-action-edit'
        | 'settings-quotation-statuscode-action-add'
        | 'settings-quotation-statuscode-action-edit'
        | 'settings-sick_leave-statuscode-action-add'
        | 'settings-sick_leave-statuscode-action-edit'
        | 'settings-work_hours-statuscode-action-add'
        | 'settings-work_hours-statuscode-action-edit'
      views:
        | never
      pathParamNames:
        | 'pk'
        | 'statuscode_pk'
    }
    'src/features/statuscode/statuscode/StatuscodeForm.vue': {
      routes:
        | 'company-statuscodes-invoice-add'
        | 'company-statuscodes-invoice-edit'
        | 'company-statuscodes-leave_hours-add'
        | 'company-statuscodes-leave_hours-edit'
        | 'company-statuscodes-order-add'
        | 'company-statuscodes-order-edit'
        | 'company-statuscodes-quotation-add'
        | 'company-statuscodes-quotation-edit'
        | 'company-statuscodes-sick_leave-add'
        | 'company-statuscodes-sick_leave-edit'
        | 'company-statuscodes-work_hours-add'
        | 'company-statuscodes-work_hours-edit'
        | 'settings-invoice-statuscode-add'
        | 'settings-invoice-statuscode-edit'
        | 'settings-leave_hours-statuscode-add'
        | 'settings-leave_hours-statuscode-edit'
        | 'settings-order-statuscode-add'
        | 'settings-order-statuscode-edit'
        | 'settings-quotation-statuscode-add'
        | 'settings-quotation-statuscode-edit'
        | 'settings-sick_leave-statuscode-add'
        | 'settings-sick_leave-statuscode-edit'
        | 'settings-work_hours-statuscode-add'
        | 'settings-work_hours-statuscode-edit'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/features/user/student/StudentUserList.vue': {
      routes:
        | 'users-studentusers'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/user/student/StudentUserForm.vue': {
      routes:
        | 'studentuser-add'
        | 'studentuser-edit'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/features/user/student/StudentRegisterForm.vue': {
      routes:
        | 'studentuser-register'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/account/ResetPasswordConfirmView.vue': {
      routes:
        | 'reset-password-confirm'
        | 'studentuser-reset-password'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/user/student/StudentRegisterVerify.vue': {
      routes:
        | 'studentuser-verify'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/user/student/StudentUserDetail.vue': {
      routes:
        | 'studentuser-detail'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/views/company/TeamleaderCallback.vue': {
      routes:
        | 'company-teamleader-callback'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/company/TeamleaderSettings.vue': {
      routes:
        | 'company-teamleader-settings'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/company/template/TemplateList.vue': {
      routes:
        | 'company-templates'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/company/template/TemplateForm.vue': {
      routes:
        | 'customer-template-add'
        | 'customer-template-edit'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/features/workforce/time-registration/TimeRegistration.vue': {
      routes:
        | 'company-time-registration'
        | 'company-time-registration-detail'
      views:
        | never
      pathParamNames:
        | 'user_id'
    }
    'src/features/workforce/leave/LeaveList.vue': {
      routes:
        | 'leave-list'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/workforce/leave/LeaveForm.vue': {
      routes:
        | 'leave-edit'
        | 'leave-list-add'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/features/workforce/leave/LeaveRequestsList.vue': {
      routes:
        | 'leave-requests'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/workforce/leave/LeaveTypes.vue': {
      routes:
        | 'leave-types'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/workforce/sick-leave/SickLeaveList.vue': {
      routes:
        | 'sick-leave-list'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/workforce/sick-leave/SickLeaveForm.vue': {
      routes:
        | 'sick-leave-list-add'
        | 'sick-leave-list-edit'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/features/workforce/sick-leave/UnconfirmedSickLeaveList.vue': {
      routes:
        | 'unconfirmed-sick-leave'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/customer/customer/CustomerList.vue': {
      routes:
        | 'customer-list'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/customer/customer/CustomerView.vue': {
      routes:
        | 'customer-dashboard'
        | 'customer-view'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/features/customer/customer/CustomerForm.vue': {
      routes:
        | 'customer-add'
        | 'customer-edit'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/features/equipment/equipment/EquipmentList.vue': {
      routes:
        | 'customers-equipment-list'
        | 'equipment-equipment-list'
        | 'settings-equipment-list'
      views:
        | never
      pathParamNames:
        | 'type'
    }
    'src/features/equipment/equipment/EquipmentDetail.vue': {
      routes:
        | 'customers-equipment-view'
        | 'customers-equipment-view-facility'
        | 'customers-equipment-view-technical'
        | 'equipment-equipment-view'
        | 'equipment-equipment-view-facility'
        | 'equipment-equipment-view-technical'
        | 'settings-equipment-view'
        | 'settings-equipment-view-facility'
        | 'settings-equipment-view-technical'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/features/equipment/equipment/EquipmentForm.vue': {
      routes:
        | 'customers-equipment-add'
        | 'customers-equipment-edit'
        | 'customers-equipment-edit-facility'
        | 'customers-equipment-edit-technical'
        | 'equipment-equipment-add'
        | 'equipment-equipment-edit'
        | 'equipment-equipment-edit-facility'
        | 'equipment-equipment-edit-technical'
        | 'settings-equipment-add'
        | 'settings-equipment-edit'
        | 'settings-equipment-edit-facility'
        | 'settings-equipment-edit-technical'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/features/equipment/location/LocationList.vue': {
      routes:
        | 'customers-location-list'
        | 'equipment-location-list'
        | 'settings-location-list'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/equipment/location/LocationDetail.vue': {
      routes:
        | 'customers-location-view'
        | 'equipment-location-view'
        | 'settings-location-view'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/features/equipment/location/LocationForm.vue': {
      routes:
        | 'customers-location-add'
        | 'customers-location-edit'
        | 'equipment-location-add'
        | 'equipment-location-edit'
        | 'settings-location-add'
        | 'settings-location-edit'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/features/customer/maintenance-contract/MaintenanceContractList.vue': {
      routes:
        | 'maintenance-contracts'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/customer/maintenance-contract/MaintenanceContractForm.vue': {
      routes:
        | 'maintenance-contract-add'
        | 'maintenance-contract-edit'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/features/customer/maintenance-contract/MaintenanceContractView.vue': {
      routes:
        | 'maintenance-contract-view'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/views/dashboard/DashboardView.vue': {
      routes:
        | 'dashboard'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/equipment/building/BuildingList.vue': {
      routes:
        | 'equipment-building-list'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/equipment/building/BuildingDetail.vue': {
      routes:
        | 'equipment-building-view'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/features/equipment/building/BuildingForm.vue': {
      routes:
        | 'equipment-building-add'
        | 'equipment-building-edit'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/views/inventory/MaterialList.vue': {
      routes:
        | 'material-list'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/inventory/MaterialForm.vue': {
      routes:
        | 'material-add'
        | 'material-edit'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/views/inventory/MaterialView.vue': {
      routes:
        | 'material-view'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/views/inventory/MaterialMoveForm.vue': {
      routes:
        | 'material-move'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/inventory/MutationList.vue': {
      routes:
        | 'mutation-list'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/inventory/MutationForm.vue': {
      routes:
        | 'mutation-add'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/inventory/PurchaseOrderEntryList.vue': {
      routes:
        | 'purchaseorder-entry-list'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/inventory/PurchaseOrderEntryForm.vue': {
      routes:
        | 'purchaseorder-entry-add'
        | 'purchaseorder-entry-edit'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/views/inventory/PurchaseOrderEntryView.vue': {
      routes:
        | 'purchaseorder-entry-view'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/views/inventory/PurchaseOrderList.vue': {
      routes:
        | 'purchaseorder-list'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/inventory/PurchaseOrderForm.vue': {
      routes:
        | 'purchaseorder-add'
        | 'purchaseorder-add-from-reservation'
        | 'purchaseorder-edit'
      views:
        | never
      pathParamNames:
        | 'pk'
        | 'reservation_pk'
    }
    'src/views/inventory/PurchaseOrderView.vue': {
      routes:
        | 'purchaseorder-view'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/views/inventory/InventoryStats.vue': {
      routes:
        | 'inventory-stats'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/inventory/StatsTable.vue': {
      routes:
        | 'inventory-stats-table'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/inventory/StockLocationList.vue': {
      routes:
        | 'stock-location-list'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/inventory/StockLocationForm.vue': {
      routes:
        | 'stock-location-add'
        | 'stock-location-edit'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/views/inventory/StockLocationView.vue': {
      routes:
        | 'stock-location-view'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/views/inventory/SupplierReservationList.vue': {
      routes:
        | 'supplier-reservation-list'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/inventory/SupplierReservationForm.vue': {
      routes:
        | 'supplier-reservation-add'
        | 'supplier-reservation-edit'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/views/inventory/SupplierReservationView.vue': {
      routes:
        | 'supplier-reservation-view'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/views/inventory/SupplierList.vue': {
      routes:
        | 'supplier-list'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/inventory/SupplierForm.vue': {
      routes:
        | 'supplier-add'
        | 'supplier-edit'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/views/inventory/SupplierView.vue': {
      routes:
        | 'supplier-view'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/features/invoice/list/InvoiceList.vue': {
      routes:
        | 'invoice-list'
        | 'invoices-sent'
        | 'preliminary-invoices'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/invoice/detail/InvoiceView.vue': {
      routes:
        | 'invoice-view'
      views:
        | never
      pathParamNames:
        | 'uuid'
    }
    'src/features/invoice/form/InvoiceForm.vue': {
      routes:
        | 'invoice-create'
        | 'invoice-edit'
      views:
        | never
      pathParamNames:
        | 'pk'
        | 'uuid'
    }
    'src/features/invoice/email/EmailForm.vue': {
      routes:
        | 'invoice-send'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/member/contract/ContractList.vue': {
      routes:
        | 'contract-list'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/member/contract/ContractForm.vue': {
      routes:
        | 'contract-add'
        | 'contract-edit'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/features/member/member/MemberList.vue': {
      routes:
        | 'member-deleted-list'
        | 'member-list'
        | 'member-requested-list'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/member/member/MemberForm.vue': {
      routes:
        | 'member-add'
        | 'member-edit'
        | 'member-request'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/features/member/module-part/ModulePartList.vue': {
      routes:
        | 'module-part-list'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/member/module-part/ModulePartForm.vue': {
      routes:
        | 'module-part-add'
        | 'module-part-edit'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/features/member/module/ModuleList.vue': {
      routes:
        | 'module-list'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/member/module/ModuleForm.vue': {
      routes:
        | 'module-add'
        | 'module-edit'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/features/field-service/dispatch/AssignedFinished.vue': {
      routes:
        | 'mobile-assigned-finished'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/field-service/dispatch/Dispatch.vue': {
      routes:
        | 'mobile-dispatch'
      views:
        | never
      pathParamNames:
        | 'assignModeProp'
    }
    'src/features/field-service/dispatch/EngineerMap.vue': {
      routes:
        | 'mobile-map'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/order/order/OrderList.vue': {
      routes:
        | 'mobile-orders'
        | 'mobile-orders-finished'
        | 'mobile-orders-in-progress'
        | 'order-list'
        | 'orders-not-accepted'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/field-service/timesheets/TimeSheet.vue': {
      routes:
        | 'mobile-timesheet'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/field-service/timesheets/TimeSheetDetail.vue': {
      routes:
        | 'mobile-timesheet-detail'
      views:
        | never
      pathParamNames:
        | 'user_id'
    }
    'src/features/field-service/trips/TripAvailability.vue': {
      routes:
        | 'mobile-trip-availability'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/field-service/trips/TripAvailabilityDetail.vue': {
      routes:
        | 'mobile-trip-availability-detail'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/features/field-service/trips/TripList.vue': {
      routes:
        | 'mobile-trips'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/field-service/trips/TripForm.vue': {
      routes:
        | 'mobile-trips-add'
        | 'mobile-trips-edit'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/features/account/NoAccessView.vue': {
      routes:
        | 'no-access'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/shared/UserFilterList.vue': {
      routes:
        | 'order-filter-list'
        | 'settings-order-filter-list'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/shared/UserFilterForm.vue': {
      routes:
        | 'order-filter-add'
        | 'order-filter-edit'
        | 'settings-order-filter-add'
        | 'settings-order-filter-edit'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/features/order/stats/MonthStats.vue': {
      routes:
        | 'order-month-stats'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/order/OrderViewByTenant.vue': {
      routes:
        | 'order-detail'
        | 'order-view'
      views:
        | never
      pathParamNames:
        | 'pk'
        | 'uuid'
    }
    'src/features/order/OrderFormByTenant.vue': {
      routes:
        | 'order-add'
        | 'order-add-maintenance'
        | 'order-add-quotation'
        | 'order-edit'
      views:
        | never
      pathParamNames:
        | 'pk'
        | 'quotation_id'
    }
    'src/features/order/workorder/WorkorderPage.vue': {
      routes:
        | 'workorder-view'
      views:
        | never
      pathParamNames:
        | 'uuid'
    }
    'src/features/order/schedule/OrdersSchedule.vue': {
      routes:
        | 'orders-schedule'
        | 'orders-schedule-params'
      views:
        | never
      pathParamNames:
        | 'end'
        | 'start'
    }
    'src/features/order/stats/YearStats.vue': {
      routes:
        | 'order-year-stats'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/dashboard/DashboardOverview.vue': {
      routes:
        | 'dashboard-overview'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/quotations/QuotationList.vue': {
      routes:
        | 'preliminary-quotations'
        | 'quotation-list'
        | 'quotations-sent'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/quotations/QuotationForm.vue': {
      routes:
        | 'quotation-add'
        | 'quotation-edit'
        | 'quotation-edit-preliminary'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/views/quotations/QuotationDetail.vue': {
      routes:
        | 'quotation-detail'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/views/quotations/QuotationView.vue': {
      routes:
        | 'quotation-view'
        | 'quotations-sent-view'
      views:
        | never
      pathParamNames:
        | 'pk'
    }
    'src/views/quotations/OfferForm.vue': {
      routes:
        | 'quotation-send'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/account/SendResetLinkView.vue': {
      routes:
        | 'reset-password'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/webshop/WebshopIframe.vue': {
      routes:
        | 'webshop'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
