export const OPTION_USER_TOTALS = 'user_totals'
export const OPTION_ONLY_TOTAL = 'total'
export const OPTION_NONE = 'none'

export const OPTION_ACTIVITY_ACTIVITY_TOTALS = 'activity_totals'
export const OPTION_ACTIVITY_ACTUAL_WORK = 'actual_work'
export const OPTION_EXTRA_WORK_TOTALS = 'extra_work_totals'
export const OPTION_USED_MATERIALS_TOTALS = 'used_materials_totals'
export const OPTION_ACTUAL_WORK_TOTALS = 'actual_work_totals'
export const OPTION_DISTANCE_TOTALS = 'distance_totals'
export const OPTION_CALL_OUT_COSTS_TOTALS = 'coc_totals'
export const OPTION_CALL_OUT_COSTS_ITEMS = 'coc_items'

export const INVOICE_LINE_TYPE_ACTIVITY = 'activity'
export const INVOICE_LINE_TYPE_USED_MATERIALS = 'used-materials'
export const INVOICE_LINE_TYPE_CALL_OUT_COSTS = 'call-out-costs'
export const INVOICE_LINE_TYPE_DISTANCE = 'distance'
export const INVOICE_LINE_TYPE_HOURS_TYPE_WORK = 'work'
export const INVOICE_LINE_TYPE_HOURS_TYPE_TRAVEL = 'travel'
export const INVOICE_LINE_TYPE_HOURS_TYPE_EXTRA_WORK = 'extra-work'
export const INVOICE_LINE_TYPE_HOURS_TYPE_ACTUAL_WORK = 'actual-work'

// new from API
export const USE_PRICE_SETTINGS = 'settings'
export const USE_PRICE_CUSTOMER = 'customer'
export const USE_PRICE_USER = 'user'
export const USE_PRICE_PURCHASE = 'purchase'
export const USE_PRICE_SELLING = 'selling'
export const USE_PRICE_OTHER = 'other'
